### ISSUE TITLE
在电脑上下载打开之后无法使用

### ISSUE THREAD

**Issue by eirms** [s282730788/RealTool#1]
作者您好，我在52pojie上看到您的帖子，下载RealTool之后打开，输入了直播间地址，按下回车键之后，没有任何反应，这是什么原因呢？

**Comment by s282730788** [comment]
原因查明了，是上版本修改过程中出现的BUG，现已修复，下载新版试试看




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "s282730788/RealTool"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年10月21日(星期五) 晚上11:16
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[s282730788/RealTool] 在电脑上下载打开之后无法使用 (Issue #1)





 
作者您好，我在52pojie上看到您的帖子，下载RealTool之后打开，输入了直播间地址，按下回车键之后，没有任何反应，这是什么原因呢？
